apiVersion: v1
kind: Deployment
metadata:
  name: tomcat
spec:
  containers:
    - image: tomcat:tomcat
      name: tomcat
      #command: ["sh", "-c", "/root/apache-tomcat-7.0.42-v2/bin/start.sh"]      
      ports:
       - containerPort: 8080
      #imagePullPolicy: Always
      #https://github.com/kubernetes/examples/tree/master/staging/javaweb-tomcat-sidecar
